/*
 * This source file was generated by the Gradle 'init' task
 */
package com.delbertina;

import org.junit.Test;

import com.delbertina.Main;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        Main classUnderTest = new Main();
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
